#!/bin/bash

# 🚀 SCRIPT PARA CRIAR ESTRUTURA SUPABASE NO MAC
# Execute este script na pasta ~/Downloads/codigo_Imob/

echo "🚀 CRIANDO ESTRUTURA SUPABASE..."

# Criar pastas
mkdir -p supabase/functions/server

echo "✅ Pastas criadas!"
echo ""
echo "📁 Estrutura criada em:"
echo "   $(pwd)/supabase/functions/server/"
echo ""
echo "🔥 AGORA VOCÊ TEM 2 OPÇÕES:"
echo ""
echo "OPÇÃO 1 (MAIS FÁCIL) - Deploy via Dashboard Supabase:"
echo "  1. Abra: https://supabase.com/dashboard/project/evdyqlrssgsktctjruuq/functions"
echo "  2. Clique em 'New Function'"
echo "  3. Nome: server"
echo "  4. Copie o código do arquivo index.tsx do Figma Make"
echo "  5. Cole no editor e faça deploy"
echo ""
echo "OPÇÃO 2 - Criar arquivos manualmente:"
echo "  Agora você precisa copiar TODOS os arquivos do Figma Make"
echo "  para a pasta supabase/functions/server/"
echo ""
echo "Lista de arquivos necessários:"
echo "  - index.tsx"
echo "  - kv_store.tsx"
echo "  - search-routes.tsx"
echo "  - auth-routes.ts"
echo "  - api-test-routes.tsx"
echo "  - apollo-api.ts"
echo "  - diagnostics-routes.ts"
echo "  - env-helper.ts"
echo "  - excel-import-routes.ts"
echo "  - instagram-routes.ts"
echo "  - intelligent-search.ts"
echo "  - leads-database.ts"
echo "  - linkedin-api.ts"
echo "  - linkedin-auth-routes.ts"
echo "  - linkedin-routes.ts"
echo "  - demo-leads-generator.ts"
echo "  - ai-brain-routes.ts"
echo "  - ai-feedback-routes.ts"
echo "  - api-proxy-routes.ts"
echo "  - ai-data-merger.ts"
echo "  - lead-helpers.ts"
echo "  - mock-data.ts"
echo "  - pdl-linkedin-api.ts"
echo "  - real-search-routes.ts"
echo "  - simple-auth.ts"
echo "  - test-startup.ts"
echo "  - web-search-service.ts"
echo ""
echo "✅ Estrutura criada com sucesso!"
